//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTZ.PlayAndAte.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItem = new HashSet<OrderItem>();
        }
    
        public int OrderId { get; set; }
        public string OrderName { get; set; }
        public int CustomerNum { get; set; }
        public decimal OrderPrice { get; set; }
        public int ProductId { get; set; }
        public int UserId { get; set; }
        public bool Success { get; set; }
        public Nullable<int> ContactsId { get; set; }
    
        public virtual Contacts Contacts { get; set; }
        public virtual Product Product { get; set; }
        public virtual UserInfo_Role UserInfo_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItem { get; set; }
    }
}
